=== Taksh01/COLLEGE-WORK/Sem3/XML_Practical/Assign2/10external.dtd
<!ELEMENT Student_info (person*)>
<!ELEMENT person (Student+,grade,Course,subject)>
<!ELEMENT Student  (name, contact_no)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT contact_no (#PCDATA)>
<!ATTLIST Student which_course IDREF #REQUIRED>
<!ATTLIST Student contactno NMTOKEN #REQUIRED>
<!ELEMENT grade (#PCDATA)>
<!ELEMENT Course (cname)>
<!ATTLIST Course c_id ID #REQUIRED>
<!ELEMENT cname (#PCDATA)>
<!ELEMENT subject (#PCDATA)>
<!ATTLIST subject name (Java|xml|OS) #REQUIRED>

=== Taksh01/COLLEGE-WORK/Sem3/XML_Practical/Assign2/10.xml
<?xml version="1.0"?>
<!DOCTYPE Student_info SYSTEM "10external.dtd">
<Student_info>
		<person>
		<Student which_course="C101" contactno="1234567898">
			<name>Vaman</name>
			<contact_no>1234567890</contact_no>
		</Student>
		
		<grade>A++</grade>
		
		<Course c_id="C101">
			<cname>CA</cname>
		</Course>
		
		<subject name="OS"></subject>
		</person>
		
		<person>
		<Student which_course="C101" contactno="1234567898">
			<name>Vaman</name>
			<contact_no>1234567890</contact_no>
		</Student>
			
				<grade>A++</grade>
				
		<Course c_id="C101">
			<cname>CA</cname>
		</Course>
		
		<subject name="Java">
		</subject>
		</person>
	</Student_info>
