=== Taksh01/COLLEGE-WORK/Sem3/XML_Practical/Assign2/11external.dtd
<!ENTITY % includePersonalInfo "INCLUDE">
<![ %includePersonalInfo;[
	<!ELEMENT studdetails (Student+)>
	<!ELEMENT 	Student (StudentName+,PersonalInfo+)>
]]>
<!ENTITY % ignoreResult "IGNORE">
<![ %ignoreResult;[
	<!ELEMENT 	Student (Result)>
]]>
<!ELEMENT StudentName (#PCDATA)>
<!ELEMENT PersonalInfo (Address, Birthdate, Gender, MobileNo)>
<!ELEMENT Address (#PCDATA)>
<!ELEMENT Birthdate (#PCDATA)>
<!ELEMENT Gender (Male|Female)>
<!ELEMENT Male (#PCDATA)>
<!ELEMENT Female (#PCDATA)>
<!ELEMENT MobileNo (#PCDATA)>

<!ELEMENT Result (Total, Percentage, Grade)>
<!ELEMENT Total (#PCDATA)>
<!ELEMENT Percentage (#PCDATA)>
<!ELEMENT Grade (Pass|First|Dist.|Second|Fail) >
<!ELEMENT Pass (#PCDATA)>
<!ELEMENT First (#PCDATA)>
<!ELEMENT Dist. (#PCDATA)>
<!ELEMENT Second (#PCDATA)>
<!ELEMENT Fail (#PCDATA)>

=== Taksh01/COLLEGE-WORK/Sem3/XML_Practical/Assign2/11.xml
<?xml version="1.0"?>
<!DOCTYPE studdetails SYSTEM "11external.dtd">
<studdetails>
<Student>
    <StudentName>John Doe</StudentName>
    <PersonalInfo>
        <Address>Jaipur</Address>
        <Birthdate>01/05/2004</Birthdate>
        <Gender>
        <Male></Male>
        </Gender>
        <MobileNo>1234567890</MobileNo>
    </PersonalInfo>
</Student>

<Student>
    <StudentName>John Doe</StudentName>
    <PersonalInfo>
        <Address>Jaipur</Address>
        <Birthdate>01/05/2004</Birthdate>
        <Gender>
        <Male></Male>
        </Gender>
        <MobileNo>1234567890</MobileNo>
    </PersonalInfo>
</Student>

</studdetails>
