=== Taksh01/COLLEGE-WORK/Sem3/XML_Practical/Assign2/1external.dtd
<!ELEMENT student (personalInfo*)>
<!ELEMENT personalInfo (rollNo, name, address, mobile, dob, age, qualification)>
<!ELEMENT rollNo (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT mobile (#PCDATA)>
<!ELEMENT dob (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT qualification (#PCDATA)>

=== Taksh01/COLLEGE-WORK/Sem3/XML_Practical/Assign2/1.xml
<?xml version="1.0"?>
<!DOCTYPE student SYSTEM "1external.dtd">
<student>
    <personalInfo>
        <rollNo>12345</rollNo>
        <name>Rohit Pandya</name>
        <address>Springfield</address>
        <mobile>1234567890</mobile>
        <dob>01/01/2000</dob>
        <age>24</age>
        <qualification>Bachelor of Science</qualification>
    </personalInfo>
    
	<personalInfo>
        <rollNo>123</rollNo>
        <name>Rohit </name>
        <address>Springfield</address>
        <mobile>1234567890</mobile>
        <dob>01-01-2000</dob>
        <age>24</age>
        <qualification>Bachelor of Arts</qualification>
	</personalInfo>
</student>
