=== Taksh01/COLLEGE-WORK/Sem3/XML_Practical/Assign2/5external.dtd
<!ELEMENT book_detail (Books*)>
<!ELEMENT Books (book,author,year,publisher)>
<!ELEMENT book (#PCDATA)>
<!ATTLIST book title (XML|DCN) #IMPLIED>
<!ELEMENT author (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>

=== Taksh01/COLLEGE-WORK/Sem3/XML_Practical/Assign2/5.xml
<?xml version="1.0"?>
<!DOCTYPE book_detail SYSTEM "5external.dtd">
	<book_detail>
		<Books>
			<book title="XML">The Art of War</book>
			<author>Sao Ten Zung</author>
			<year>2005</year>
			<publisher>Readdit</publisher>
		</Books>
		
		<Books>
			<book title="DCN">5AM Club</book>
			<author>Robin Parikh</author>
			<year>2015</year>
			<publisher>Jaico</publisher>
		</Books>
	</book_detail>
