=== Taksh01/COLLEGE-WORK/Sem3/XML_Practical/Assign2/8external.dtd
<!ELEMENT Students (student*)>
<!ELEMENT student (Roll_No , name , marks , rank)>
<!ELEMENT Roll_No (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT marks (webtechnologies|XML|J2EE|NS)*>
<!ELEMENT webtechnologies (#PCDATA)>
<!ELEMENT XML (#PCDATA)>
<!ELEMENT J2EE (#PCDATA)>
<!ELEMENT NS (#PCDATA)>
<!ELEMENT rank (#PCDATA)>

=== Taksh01/COLLEGE-WORK/Sem3/XML_Practical/Assign2/8.xml
<?xml version="1.0"?>
<!DOCTYPE Students SYSTEM "8external.dtd">
	<Students>
		<student>
			<Roll_No>1234</Roll_No>
			<name>Tarak Mehta</name>
			<marks>
			<webtechnologies></webtechnologies>
			<XML></XML>
			<J2EE></J2EE>
			</marks>
			<rank>116</rank>
		</student>
		
		<student>
			<Roll_No>1444</Roll_No>
			<name>Mr.Iyer</name>
			<marks>
		
			<XML></XML>
			<J2EE></J2EE>
			<NS></NS>
			</marks>
			<rank>106</rank>
		</student>
	</Students>
